name: Deploy to Firebase Hosting (STG)

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.0.0]
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POKEMON_SHUZOKUCHI_QUIZ_STG }}'
          projectId: pokemon-shuzokuchi-quiz-stg
          channelId: live
