name: Deploy to Firebase Hosting (STG)

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.0.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Build and Export
        run: |
          yarn run build
          yarn run export
      - name: deploy to Firebase Hosting
        run: |
          yarn deploy --token=${{ secrets.FIREBASE_SERVICE_ACCOUNT_POKEMON_SHUZOKUCHI_QUIZ_STG }}
