name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ./.node-version
      - name: Install dependencies
        run: npm ci
      - name: Build and Export
        run: |
          npm run build
          npm run export
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: Deploy to Production
        run: |
          firebase use pokemon-shuzokuchi-quiz
          firebase deploy --only hosting:production
