name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install
      - name: Build and Export
        run: |
          yarn run build
          yarn run export
        env:
          GITHUB_PAGES: true
      - name: Add nojekyll
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
